import type { Metadata } from 'next';
import { Roboto, Rubik_Scribble } from 'next/font/google';
import './globals.css';
import localFont from 'next/font/local';

// const inter = Inter({ subsets: ['latin'] });
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500'],
  style: ['normal', 'italic'],
  variable: '--roboto-text',
});

const rubik = Rubik_Scribble({
  subsets: ['latin'],
  weight: '400',
  style: 'normal',
  variable: '--rubik-text',
});

const spoca = localFont({
  src: './SpoqaHanSansNeo-Regular.ttf',
  variable: '--spoca-text',
});

export const metadata: Metadata = {
  title: {
    template: '%s | Carrot Market',
    default: 'Carrot Market',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='bg-neutral-900 text-neutral-50'>
      <body
        className={`${roboto.variable} ${rubik.variable} ${spoca.variable} max-w-screen-md mx-auto`}
      >
        {children}
      </body>
    </html>
  );
}
