import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    template: '%s | Carrot Market',
    default: 'Carrot Market',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='bg-neutral-900 text-neutral-50'>
      <body className={`${inter.className} max-w-screen-md mx-auto`}>
        {children}
      </body>
    </html>
  );
}
